### ISSUE TITLE
Cleanup OKH-LOSH.ttl

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#101]
there are still some obsolete MOSH/POSH references in the comments and hence (maybe) redundant fields

**Comment by hoijui** [comment]
We convert one machine-readable format (TOML) into an other (RDF/Turtle).
I think it would make sense (and should be easy), to document this mapping in a (at least quasi-)machine-readable way.
I imagine pseudo-code within the RDF ontology,
where each property defines how it is derived from TOML.
This seems a good spot to document this, because anyone who is interested in the mapping from TOML to RDF needs to understand RDF anyway, and at least when changing the RDF, it comes natural to change this mapping too, at the same time, if required.

example (Note the added `okh:fromManifestMapping` lines):

```turtle
okh:repository
  a owl:ObjectProperty ;
  rdfs:label "repository" ;
  rdfs:comment '''
    URL to the place where development happens (typically the repository)" ;
    following this link people shall be able to contribute to the development
    (reporting issues, suggesting changes, connecting to the team etc.)" '''@en;
  okh:fromManifestMapping "{repo}" ;
  rdfs:subPropertyOf schema:codeRepository ;
  rdfs:range okh:WebsiteURL ;
  owl:cardinality 1 ;
  rdfs:domain okh:Module ;
  .

okh:repoSnapshot
  a owl:ObjectProperty ;
  rdfs:label "URL respository snapshot (=specific version)" ;
  rdfs:comment "LOSH-Krawler takes the commit hash from the version tag and creates this permalink" ;
  okh:fromManifestMapping "{repo}/tree/{version}/" ;
  rdfs:subPropertyOf okh:repository ;
  rdfs:range okh:WebsiteURL ;
  owl:cardinality 1 ;
  rdfs:domain okh:Module ;
  .

okh:version
  a owl:DatatypeProperty ;
  rdfs:label "version" ;
  rdfs:comment "version of this Component, preferably in the semantic versioning scheme (semver.org)" ;
  okh:fromManifestMapping "{version}" ;
  rdfs:subPropertyOf schema:version ;
  rdfs:domain okh:Module ;
  owl:cardinality 1
  .
```

**Comment by hoijui** [comment]
The original issue is long resolved, and the separate idea is now in a separate, new issue.
