### ISSUE TITLE
register ontology at PURL and the internet archive

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/OKH-LOSH#80]
- [ ] PURL
- [ ] [internet archive](https://archive.org/services/purl/)

**Comment by penyuan** [comment]
Sorry superflous comment first: I'm stoked to finally meet another person who knows about PURL (or the Internet Archive for that matter).

For PURL, is it to link to this repository?

As for the Internet Archive, are we just uploading a copy of this repository?

**Comment by moedn** [comment]
@hoijui for professional reply :D (he's the holder of actual knowledge in this matter)

**Comment by hoijui** [comment]
a wee bit late...
[PURL](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator) is an alias for a URL, similar like a UNIX symbolic link in the file-system.
So you can register an account at PURL, and you get a URL prefix (something like `purl.org/oseg`), and through their web interface, you can create paths under that prefix, and define where they link to. You can later change where they link to.
So when your project is on github you can link to there, and if you later move to gitlab, you can just change that aliases link target. This way, the URL a file/dir is available under can stay the same over time, with things changeing.
It also allows you to worry less about which hosting provider you use, for example.

the internet archive is just one (maybe the most used and trustworthy) provider of such a service.

as I get it, this issue is not about storing data at the internet archive, but just about registering a PURL.

**Comment by hoijui** [comment]
We _are_ now registered at/using a PURL; specifically `w3id.org`,
which is the standard one these days, and is carried and backed by a wide range of big organizations,
while also being technically done simpler, more robust and.. in all ways better!

**Comment by hoijui** [comment]
Related: https://github.com/OPEN-NEXT/OKH-LOSH/issues/125
